events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # VULN: no HTTPS, no security headers, server version exposed
    server_tokens on;

    upstream flask_app {
        server app:5000;
    }

    server {
        listen 80;
        server_name _;

        # VULN: no security headers (X-Frame-Options, CSP, HSTS, etc.)

        location /static/ {
            alias /var/www/static/;
            # VULN: directory listing enabled
            autoindex on;
        }

        location / {
            proxy_pass http://flask_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
